---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cm
  namespace: redis
data:
  redis.conf: |
    port 6379
    appendonly yes
    bind 0.0.0.0
    dir /data
    maxmemory 75mb
    maxmemory-policy allkeys-lru
    protected-mode no
  sentinel.conf: |
    port 26379
    bind 0.0.0.0
    protected-mode no
    sentinel resolve-hostnames yes
    sentinel monitor mymaster redis-sts-0.redis-hl.redis.svc.cluster.local 6379 2
    sentinel down-after-milliseconds mymaster 5000
    sentinel failover-timeout mymaster 60000
    sentinel parallel-syncs mymaster 1
