---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cm
  namespace: redis
data:
  redis.conf: |
    port 6379
    appendonly yes
    bind 0.0.0.0
    dir /data
    maxmemory 75mb
    maxmemory-policy allkeys-lru
    protected-mode no

